FROM python:3.13-slim

WORKDIR /app

COPY . .

# Set environment variable to disable Python output buffering
ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir pdm && \
    pdm install --no-self && \
    chmod -R 777 /app/data && \
    chmod +x /app/docker-entrypoint.sh

# Add entrypoint
ENTRYPOINT ["/app/docker-entrypoint.sh"]

# Set the command to run the runner script
CMD ["pdm", "run", "python", "runner.py"] 